#
# Build Stage
#
FROM node:14-buster-slim as build
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile


#
# Package Stage
#
COPY . ./
RUN yarn build
FROM nginx:1.21-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
