#
# Build Stage
#
FROM node:14-buster-slim as builder
ENV NODE_ENV production
WORKDIR /app
COPY ./package.json ./
RUN npm install


#
# Package Stage
#
COPY . ./
RUN npm run build
FROM nginx
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
